source :rubygems

gem 'rails', '3.2.3'

group :development do
  gem 'annotate'
end

group :development, :test do
  gem 'sqlite3', '~> 1.3.6'
  gem 'awesome_print'
end

group :test do
end

group :staging, :production do
end

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'simple_enum'
